
CONFIG_ZMK_SLEEP=y

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE=y
#CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y


CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y

# CONFIG_PMW3610_ALT_SWAP_XY=y // <-- deprecated, use swap-xy; instead
# CONFIG_PMW3610_ALT_INVERT_X=y // <-- deprecated, use invert-x; instead
# CONFIG_PMW3610_ALT_INVERT_Y=y // <-- deprecated, use invert-y; instead
# CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=12
CONFIG_PMW3610_ALT_LOG_LEVEL_DBG=y
#CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=300 // <--see Troubleshooting
CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=1000

# CONFIG_PMW3610_SWAP_XY=y
# CONFIG_PMW3610_INVERT_X=y
#CONFIG_PMW3610_INVERT_Y=y
#CONFIG_PMW3610_SMART_ALGORITHM=y
###CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=30

# Idle State: 2 min
#CONFIG_ZMK_IDLE_TIMEOUT=120000
# Deep Sleep: 30 min
#CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

#CONFIG_ZMK_EXT_POWER=y

##CONFIG_ZMK_MOUSE=y


#CONFIG_PMW3610_SWAP_XY=y

CONFIG_ZMK_INPUT_PROCESSOR_ROTATE_PLANE=y


# Turn on logging, and set ZMK logging to debug output
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG=y
CONFIG_ZMK_LOG_LEVEL_DBG=y
